version: '2.4'
services:

  postgres:
    container_name: postgres
    image: postgres:10-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: "tcia"
      POSTGRES_PASSWORD: "tcia_password"
      POSTGRES_DB: "orthanc"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  dicom:
    container_name: dicom
    build: ./dicom
    depends_on:
      - postgres
    ports:
      - "4242:4242"
      - "8042:8042"
    volumes:
      - ./db/dicom:/var/lib/orthanc/db
      - ./dicom:/app/dicom
      - ./dicom/orthanc.json:/etc/orthanc/orthanc.json
    environment:
      PGHOST: "postgres"
      PGUSER: "tcia"
      PGPASSWORD: "tcia_password"
      PGDATABASE: "orthanc"
      PGPORT: "5432"
      VERBOSE: "--verbose"
      COLLECTION: ""

volumes:
  esdata:
    driver: local
